# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_class', models.CharField(max_length=100)),
                ('skill_categories', models.CharField(max_length=200)),
                ('skill_priority', models.IntegerField(default=99)),
                ('skill_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('skill_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_category_name', models.CharField(max_length=200)),
                ('skill_category_priority', models.IntegerField(default=99)),
                ('skill_category_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkillDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail_name', models.CharField(max_length=200)),
                ('detail_class', models.CharField(max_length=100)),
                ('detail_categories', models.CharField(max_length=200)),
                ('detail_description', models.TextField(blank='TRUE', max_length=500, null='TRUE')),
                ('detail_priority', models.IntegerField(default=99)),
                ('detail_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill_foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desai.Skill')),
            ],
        ),
    ]
