# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desai', '0002_auto_20160302_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilldetail',
            name='detail_description',
            field=models.TextField(blank='TRUE', max_length=500, null='TRUE'),
        ),
    ]
