# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desai', '0003_auto_20160302_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_priority',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='skilldetail',
            name='detail_priority',
            field=models.IntegerField(default=99),
        ),
    ]
