# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desai', '0005_auto_20160302_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilldetail',
            name='id',
        ),
        migrations.AddField(
            model_name='skilldetail',
            name='detail_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
