# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desai', '0006_auto_20160302_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='skilldetail',
            name='detail_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
